### ISSUE TITLE
Profile pop-out broken (Powercord)

### ISSUE THREAD

**Issue by gwennshinguji** [hellbound1337/dark-discord#4] opened 2020-06-16 23:47 UTC
[Example](https://postimg.cc/7GvK8dxw)

**Issue:** Pop-out notes + roles section reverts to default theme when it should be the same dark colour as the rest of the theme.

**Powercord version:** `f8180d3`
**Dark Discord version:** `9946f1c`

**Comment by hellbound1337** [comment] 2020-06-16 23:55
I can't reproduce this, where exactly are you opening the profile popout from?

**Comment by gwennshinguji** [comment] 2020-06-17 00:54
just clicking on a name in a group/DM brings up a small window, and that's where I have that issue.

**Comment by hellbound1337** [comment] 2020-06-17 01:00
https://media.wtf/66787032 it looks fine for me?

**Comment by hellbound1337** [comment] 2020-06-17 02:06
Could you provide a video?

**Comment by hellbound1337** [comment] 2020-06-17 10:43
Fixed with [1361185](https://github.com/hellbound1337/dark-discord/commit/136118517cf49a20c954ab8d0475e9780a363952)

**Closed** 2020-06-17 10:43 UTC
